### ISSUE TITLE
Milestone 3 part 2 - implementation

### ISSUE THREAD

**Issue by lsteiner9** [tunefull/tunefull#1]
[Rubric](https://ddc-java-11.github.io/2020/11/30/capstone-project-milestone-3-rubric/)

Items that are new elements of the project (or will require lots of work) are in **bold**.

Implementation: (55 pts)
- [ ] **Intuitive GUI** (9pts)
- [ ] **Efficient, reliable communication between component platforms** (12pts)
- [x] **Effective use of databases (relational or non-relational) for maintaining persistent data** (10pts)
- [ ] **Database-driven display of/interaction with model object collections** (10pts)
- [ ] **Consumption of external data or services** (8pts)
- [ ] **Custom icons and other graphics** (6pts)
